# site settings
title: tuckersylvia.com
author: Tucker Sylvia
description: "My personnal space on the web"

theme: jekyll-theme-midnight

# build settings
port: 4000
highlighter: rouge # rouge not rogue 
# apparently github pages doesnt like pygments as the highlighter
# I might start building locally and pushing to the repo especially if I start using other plugins etc.
markdown: kramdown
# again the github pages builder complained, about redcarpet this time, 
# once again making me think building locally is a better option
permalink: pretty
