---
title: Proceptive Insights
timezone: America/New_York

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: "_posts"
    type: posts
  values:
    layout: post
    published: true
    mathjax: false
    author: Tucker Sylvia

author: Tucker Sylvia
email: proception@gmail.com
description: 'My personnal space on the web to blog about problems I solve and other
  tidbits worth sharing.'

baseurl: ''
url: http://tuckersylvia.com
github_username: tuckersylvia
twitter_username: proceptionable

twitter:
  username: proceptionable

facebook:
  publisher: https://www.facebook.com/tucker.sylvia

logo: /assets/icons/favicomatic/favicon-128.printing

social:
  name: Tucker sylvia
  links:
    - https://twitter.com/proceptionable
    - https://www.facebook.com/tucker.Sylvia
    - https://www.linkedin.com/in/tucker-sylvia
    - https://github.com/tuckersylvia

webmaster_verification:
  google: 0MMhBP5h0X5Bo6_bZmMJrBk_AQmVr8z7-ZgXg7BkazI

repository: tuckersylvia/tuckersylvia.github.io
theme: jekyll-theme-midnight
port: 4000

highlighter: rouge
markdown: kramdown
permalink: pretty

include:
- _pages

exclude:
- TODO.txt
- Gemfile
- Gemfile.lock

keep_files:


kramdown:
  input: GFM

plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
